"""Add price column to MenuItem model

Revision ID: 838cfbf31917
Revises: 483f8e4e0d15
Create Date: 2024-10-22 15:50:25.434165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '838cfbf31917'
down_revision = '483f8e4e0d15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
