"""Add OrderItem model and calculate order price

Revision ID: 8edb7440fccd
Revises: 838cfbf31917
Create Date: 2024-10-22 16:32:03.305308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8edb7440fccd'
down_revision = '838cfbf31917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Float(), nullable=False))
        batch_op.drop_column('item')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('item', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###
